[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_memory_issue = "7ADHtPbzx2msHbiKu1fEBwP8u2eePGRU6WCz4f55cVpg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/imran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
