[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_memory_issue = "5ge4JgXdpwr87y3nDWX2e4Te8neCDwAX9X6LG7Rptez7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/imran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
